erDiagram
    Crime ||--|| "CJS Common Platform" : uses
    CFT ||--|| "Cloud Native Platform" : uses
    SDS ||--|| "Cloud Native Platform" : uses
    Legacy ||--|{ "Various Platforms" : uses
    Legacy ||--|| "Cloud Native Platform" : uses
